project:
  model:
    internal: ""
    external: "PDA5_MU"
  chip:
    platform: "SM4350Pro"
  version:
    android: "V"
  date: "250224"
  baseline: "Mannar.LA.2.5.1"
  repo_root_path: "UZQ00801_PDA5_SM4350Pro_V_241111"
